<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountriesSeeder extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        Country::truncate();
        $countries = [
            ["sortname" => "AF",  "phonecode" =>    93, "name"  => "Afghanistan"],
            ["sortname" => "AL",  "phonecode" =>   355, "name"  => "Albania"],
            ["sortname" => "DZ",  "phonecode" =>   213, "name"  => "Algeria"],
            ["sortname" => "AS",  "phonecode" =>  1684, "name"  => "American Samoa"],
            ["sortname" => "AD",  "phonecode" =>   376, "name"  => "Andorra"],
            ["sortname" => "AO",  "phonecode" =>   244, "name"  => "Angola"],
            ["sortname" => "AI",  "phonecode" =>  1264, "name"  => "Anguilla"],
            ["sortname" => "AQ",  "phonecode" =>     0, "name"  => "Antarctica"],
            ["sortname" => "AG",  "phonecode" =>  1268, "name"  => "Antigua And Barbuda"],
            ["sortname" => "AR",  "phonecode" =>    54, "name"  => "Argentina"],
            ["sortname" => "AM",  "phonecode" =>   374, "name"  => "Armenia"],
            ["sortname" => "AW",  "phonecode" =>   297, "name"  => "Aruba"],
            ["sortname" => "AU",  "phonecode" =>    61, "name"  => "Australia"],
            ["sortname" => "AT",  "phonecode" =>    43, "name"  => "Austria"],
            ["sortname" => "AZ",  "phonecode" =>   994, "name"  => "Azerbaijan"],
            ["sortname" => "BS",  "phonecode" =>  1242, "name"  => "Bahamas The"],
            ["sortname" => "BH",  "phonecode" =>   973, "name"  => "Bahrain"],
            ["sortname" => "BD",  "phonecode" =>   880, "name"  => "Bangladesh"],
            ["sortname" => "BB",  "phonecode" =>  1246, "name"  => "Barbados"],
            ["sortname" => "BY",  "phonecode" =>   375, "name"  => "Belarus"],
            ["sortname" => "BE",  "phonecode" =>    32, "name"  => "Belgium"],
            ["sortname" => "BZ",  "phonecode" =>   501, "name"  => "Belize"],
            ["sortname" => "BJ",  "phonecode" =>   229, "name"  => "Benin"],
            ["sortname" => "BM",  "phonecode" =>  1441, "name"  => "Bermuda"],
            ["sortname" => "BT",  "phonecode" =>   975, "name"  => "Bhutan"],
            ["sortname" => "BO",  "phonecode" =>   591, "name"  => "Bolivia"],
            ["sortname" => "BA",  "phonecode" =>   387, "name"  => "Bosnia and Herzegovina"],
            ["sortname" => "BW",  "phonecode" =>   267, "name"  => "Botswana"],
            ["sortname" => "BV",  "phonecode" =>     0, "name"  => "Bouvet Island"],
            ["sortname" => "BR",  "phonecode" =>    55, "name"  => "Brazil"],
            ["sortname" => "IO",  "phonecode" =>   246, "name"  => "British Indian Ocean Territory"],
            ["sortname" => "BN",  "phonecode" =>   673, "name"  => "Brunei"],
            ["sortname" => "BG",  "phonecode" =>   359, "name"  => "Bulgaria"],
            ["sortname" => "BF",  "phonecode" =>   226, "name"  => "Burkina Faso"],
            ["sortname" => "BI",  "phonecode" =>   257, "name"  => "Burundi"],
            ["sortname" => "KH",  "phonecode" =>   855, "name"  => "Cambodia"],
            ["sortname" => "CM",  "phonecode" =>   237, "name"  => "Cameroon"],
            ["sortname" => "CA",  "phonecode" =>     1, "name"  => "Canada"],
            ["sortname" => "CV",  "phonecode" =>   238, "name"  => "Cape Verde"],
            ["sortname" => "KY",  "phonecode" =>  1345, "name"  => "Cayman Islands"],
            ["sortname" => "CF",  "phonecode" =>   236, "name"  => "Central African Republic"],
            ["sortname" => "TD",  "phonecode" =>   235, "name"  => "Chad"],
            ["sortname" => "CL",  "phonecode" =>    56, "name"  => "Chile"],
            ["sortname" => "CN",  "phonecode" =>    86, "name"  => "China"],
            ["sortname" => "CX",  "phonecode" =>    61, "name"  => "Christmas Island"],
            ["sortname" => "CC",  "phonecode" =>   672, "name"  => "Cocos (Keeling) Islands"],
            ["sortname" => "CO",  "phonecode" =>    57, "name"  => "Colombia"],
            ["sortname" => "KM",  "phonecode" =>   269, "name"  => "Comoros"],
            ["sortname" => "CG",  "phonecode" =>   242, "name"  => "Republic Of The Congo"],
            ["sortname" => "CD",  "phonecode" =>   242, "name"  => "Democratic Republic Of The Congo"],
            ["sortname" => "CK",  "phonecode" =>   682, "name"  => "Cook Islands"],
            ["sortname" => "CR",  "phonecode" =>   506, "name"  => "Costa Rica"],
            ["sortname" => "CI",  "phonecode" =>   225, "name"  => "Cote D'Ivoire (Ivory Coast)"],
            ["sortname" => "HR",  "phonecode" =>   385, "name"  => "Croatia (Hrvatska)"],
            ["sortname" => "CU",  "phonecode" =>    53, "name"  => "Cuba"],
            ["sortname" => "CY",  "phonecode" =>   357, "name"  => "Cyprus"],
            ["sortname" => "CZ",  "phonecode" =>   420, "name"  => "Czech Republic"],
            ["sortname" => "DK",  "phonecode" =>    45, "name"  => "Denmark"],
            ["sortname" => "DJ",  "phonecode" =>   253, "name"  => "Djibouti"],
            ["sortname" => "DM",  "phonecode" =>  1767, "name"  => "Dominica"],
            ["sortname" => "DO",  "phonecode" =>  1809, "name"  => "Dominican Republic"],
            ["sortname" => "TP",  "phonecode" =>   670, "name"  => "East Timor"],
            ["sortname" => "EC",  "phonecode" =>   593, "name"  => "Ecuador"],
            ["sortname" => "EG",  "phonecode" =>    20, "name"  => "Egypt"],
            ["sortname" => "SV",  "phonecode" =>   503, "name"  => "El Salvador"],
            ["sortname" => "GQ",  "phonecode" =>   240, "name"  => "Equatorial Guinea"],
            ["sortname" => "ER",  "phonecode" =>   291, "name"  => "Eritrea"],
            ["sortname" => "EE",  "phonecode" =>   372, "name"  => "Estonia"],
            ["sortname" => "ET",  "phonecode" =>   251, "name"  => "Ethiopia"],
            ["sortname" => "XA",  "phonecode" =>    61, "name"  => "External Territories of Australia"],
            ["sortname" => "FK",  "phonecode" =>   500, "name"  => "Falkland Islands"],
            ["sortname" => "FO",  "phonecode" =>   298, "name"  => "Faroe Islands"],
            ["sortname" => "FJ",  "phonecode" =>   679, "name"  => "Fiji Islands"],
            ["sortname" => "FI",  "phonecode" =>   358, "name"  => "Finland"],
            ["sortname" => "FR",  "phonecode" =>    33, "name"  => "France"],
            ["sortname" => "GF",  "phonecode" =>   594, "name"  => "French Guiana"],
            ["sortname" => "PF",  "phonecode" =>   689, "name"  => "French Polynesia"],
            ["sortname" => "TF",  "phonecode" =>     0, "name"  => "French Southern Territories"],
            ["sortname" => "GA",  "phonecode" =>   241, "name"  => "Gabon"],
            ["sortname" => "GM",  "phonecode" =>   220, "name"  => "Gambia The"],
            ["sortname" => "GE",  "phonecode" =>   995, "name"  => "Georgia"],
            ["sortname" => "DE",  "phonecode" =>    49, "name"  => "Germany"],
            ["sortname" => "GH",  "phonecode" =>   233, "name"  => "Ghana"],
            ["sortname" => "GI",  "phonecode" =>   350, "name"  => "Gibraltar"],
            ["sortname" => "GR",  "phonecode" =>    30, "name"  => "Greece"],
            ["sortname" => "GL",  "phonecode" =>   299, "name"  => "Greenland"],
            ["sortname" => "GD",  "phonecode" =>  1473, "name"  => "Grenada"],
            ["sortname" => "GP",  "phonecode" =>   590, "name"  => "Guadeloupe"],
            ["sortname" => "GU",  "phonecode" =>  1671, "name"  => "Guam"],
            ["sortname" => "GT",  "phonecode" =>   502, "name"  => "Guatemala"],
            ["sortname" => "XU",  "phonecode" =>    44, "name"  => "Guernsey and Alderney"],
            ["sortname" => "GN",  "phonecode" =>   224, "name"  => "Guinea"],
            ["sortname" => "GW",  "phonecode" =>   245, "name"  => "Guinea-Bissau"],
            ["sortname" => "GY",  "phonecode" =>   592, "name"  => "Guyana"],
            ["sortname" => "HT",  "phonecode" =>   509, "name"  => "Haiti"],
            ["sortname" => "HM",  "phonecode" =>     0, "name"  => "Heard and McDonald Islands"],
            ["sortname" => "HN",  "phonecode" =>   504, "name"  => "Honduras"],
            ["sortname" => "HK",  "phonecode" =>   852, "name"  => "Hong Kong S.A.R."],
            ["sortname" => "HU",  "phonecode" =>    36, "name"  => "Hungary"],
            ["sortname"  => "IS",   "phonecode" =>   354, "name" =>  "Iceland"],
            ["sortname"  => "IN",   "phonecode" =>    91, "name" =>  "India"],
            ["sortname"  => "ID",   "phonecode" =>    62, "name" =>  "Indonesia"],
            ["sortname"  => "IR",   "phonecode" =>    98, "name" =>  "Iran"],
            ["sortname"  => "IQ",   "phonecode" =>   964, "name" =>  "Iraq"],
            ["sortname"  => "IE",   "phonecode" =>   353, "name" =>  "Ireland"],
            ["sortname"  => "IL",   "phonecode" =>   972, "name" =>  "Israel"],
            ["sortname"  => "IT",   "phonecode" =>    39, "name" =>  "Italy"],
            ["sortname"  => "JM",   "phonecode" =>  1876, "name" =>  "Jamaica"],
            ["sortname"  => "JP",   "phonecode" =>    81, "name" =>  "Japan"],
            ["sortname"  => "XJ",   "phonecode" =>    44, "name" =>  "Jersey"],
            ["sortname"  => "JO",   "phonecode" =>   962, "name" =>  "Jordan"],
            ["sortname"  => "KZ",   "phonecode" =>     7, "name" =>  "Kazakhstan"],
            ["sortname"  => "KE",   "phonecode" =>   254, "name" =>  "Kenya"],
            ["sortname"  => "KI",   "phonecode" =>   686, "name" =>  "Kiribati"],
            ["sortname"  => "KP",   "phonecode" =>   850, "name" =>  "Korea North"],
            ["sortname"  => "KR",   "phonecode" =>    82, "name" =>  "Korea South"],
            ["sortname"  => "KW",   "phonecode" =>   965, "name" =>  "Kuwait"],
            ["sortname"  => "KG",   "phonecode" =>   996, "name" =>  "Kyrgyzstan"],
            ["sortname"  => "LA",   "phonecode" =>   856, "name" =>  "Laos"],
            ["sortname"  => "LV",   "phonecode" =>   371, "name" =>  "Latvia"],
            ["sortname"  => "LB",   "phonecode" =>   961, "name" =>  "Lebanon"],
            ["sortname"  => "LS",   "phonecode" =>   266, "name" =>  "Lesotho"],
            ["sortname"  => "LR",   "phonecode" =>   231, "name" =>  "Liberia"],
            ["sortname"  => "LY",   "phonecode" =>   218, "name" =>  "Libya"],
            ["sortname"  => "LI",   "phonecode" =>   423, "name" =>  "Liechtenstein"],
            ["sortname"  => "LT",   "phonecode" =>   370, "name" =>  "Lithuania"],
            ["sortname"  => "LU",   "phonecode" =>   352, "name" =>  "Luxembourg"],
            ["sortname"  => "MO",   "phonecode" =>   853, "name" =>  "Macau S.A.R."],
            ["sortname"  => "MK",   "phonecode" =>   389, "name" =>  "Macedonia"],
            ["sortname"  => "MG",   "phonecode" =>   261, "name" =>  "Madagascar"],
            ["sortname"  => "MW",   "phonecode" =>   265, "name" =>  "Malawi"],
            ["sortname"  => "MY",   "phonecode" =>    60, "name" =>  "Malaysia"],
            ["sortname"  => "MV",   "phonecode" =>   960, "name" =>  "Maldives"],
            ["sortname"  => "ML",   "phonecode" =>   223, "name" =>  "Mali"],
            ["sortname"  => "MT",   "phonecode" =>   356, "name" =>  "Malta"],
            ["sortname"  => "XM",   "phonecode" =>    44, "name" =>  "Man (Isle of)"],
            ["sortname"  => "MH",   "phonecode" =>   692, "name" =>  "Marshall Islands"],
            ["sortname"  => "MQ",   "phonecode" =>   596, "name" =>  "Martinique"],
            ["sortname"  => "MR",   "phonecode" =>   222, "name" =>  "Mauritania"],
            ["sortname"  => "MU",   "phonecode" =>   230, "name" =>  "Mauritius"],
            ["sortname"  => "YT",   "phonecode" =>   269, "name" =>  "Mayotte"],
            ["sortname"  => "MX",   "phonecode" =>    52, "name" =>  "Mexico"],
            ["sortname"  => "FM",   "phonecode" =>   691, "name" =>  "Micronesia"],
            ["sortname"  => "MD",   "phonecode" =>   373, "name" =>  "Moldova"],
            ["sortname"  => "MC",   "phonecode" =>   377, "name" =>  "Monaco"],
            ["sortname"  => "MN",   "phonecode" =>   976, "name" =>  "Mongolia"],
            ["sortname"  => "MS",   "phonecode" =>  1664, "name" =>  "Montserrat"],
            ["sortname"  => "MA",   "phonecode" =>   212, "name" =>  "Morocco"],
            ["sortname"  => "MZ",   "phonecode" =>   258, "name" =>  "Mozambique"],
            ["sortname"  => "MM",   "phonecode" =>    95, "name" =>  "Myanmar"],
            ["sortname"  => "NA",   "phonecode" =>   264, "name" =>  "Namibia"],
            ["sortname"  => "NR",   "phonecode" =>   674, "name" =>  "Nauru"],
            ["sortname"  => "NP",   "phonecode" =>   977, "name" =>  "Nepal"],
            ["sortname"  => "AN",   "phonecode" =>   599, "name" =>  "Netherlands Antilles"],
            ["sortname"  => "NL",   "phonecode" =>    31, "name" =>  "Netherlands The"],
            ["sortname"  => "NC",   "phonecode" =>   687, "name" =>  "New Caledonia"],
            ["sortname"  => "NZ",   "phonecode" =>    64, "name" =>  "New Zealand"],
            ["sortname"  => "NI",   "phonecode" =>   505, "name" =>  "Nicaragua"],
            ["sortname"  => "NE",   "phonecode" =>   227, "name" =>  "Niger"],
            ["sortname"  => "NG",   "phonecode" =>   234, "name" =>  "Nigeria"],
            ["sortname"  => "NU",   "phonecode" =>   683, "name" =>  "Niue"],
            ["sortname"  => "NF",   "phonecode" =>   672, "name" =>  "Norfolk Island"],
            ["sortname"  => "MP",   "phonecode" =>  1670, "name" =>  "Northern Mariana Islands"],
            ["sortname"  => "NO",   "phonecode" =>    47, "name" =>  "Norway"],
            ["sortname"  => "OM",   "phonecode" =>   968, "name" =>  "Oman"],
            ["sortname"  => "PK",   "phonecode" =>    92, "name" =>  "Pakistan"],
            ["sortname"  => "PW",   "phonecode" =>   680, "name" =>  "Palau"],
            ["sortname"  => "PS",   "phonecode" =>   970, "name" =>  "Palestinian Territory Occupied"],
            ["sortname"  => "PA",   "phonecode" =>   507, "name" =>  "Panama"],
            ["sortname"  => "PG",   "phonecode" =>   675, "name" =>  "Papua new Guinea"],
            ["sortname"  => "PY",   "phonecode" =>   595, "name" =>  "Paraguay"],
            ["sortname"  => "PE",   "phonecode" =>    51, "name" =>  "Peru"],
            ["sortname"  => "PH",   "phonecode" =>    63, "name" =>  "Philippines"],
            ["sortname"  => "PN",   "phonecode" =>     0, "name" =>  "Pitcairn Island"],
            ["sortname"  => "PL",   "phonecode" =>    48, "name" =>  "Poland"],
            ["sortname"  => "PT",   "phonecode" =>   351, "name" =>  "Portugal"],
            ["sortname"  => "PR",   "phonecode" =>  1787, "name" =>  "Puerto Rico"],
            ["sortname"  => "QA",   "phonecode" =>   974, "name" =>  "Qatar"],
            ["sortname"  => "RE",   "phonecode" =>   262, "name" =>  "Reunion"],
            ["sortname"  => "RO",   "phonecode" =>    40, "name" =>  "Romania"],
            ["sortname"  => "RU",   "phonecode" =>    70, "name" =>  "Russia"],
            ["sortname"  => "RW",   "phonecode" =>   250, "name" =>  "Rwanda"],
            ["sortname"  => "SH",   "phonecode" =>   290, "name" =>  "Saint Helena"],
            ["sortname"  => "KN",   "phonecode" =>  1869, "name" =>  "Saint Kitts And Nevis"],
            ["sortname"  => "LC",   "phonecode" =>  1758, "name" =>  "Saint Lucia"],
            ["sortname"  => "PM",   "phonecode" =>   508, "name" =>  "Saint Pierre and Miquelon"],
            ["sortname"  => "VC",   "phonecode" =>  1784, "name" =>  "Saint Vincent And The Grenadines"],
            ["sortname"  => "WS",   "phonecode" =>   684, "name" =>  "Samoa"],
            ["sortname"  => "SM",   "phonecode" =>   378, "name" =>  "San Marino"],
            ["sortname"  => "ST",   "phonecode" =>   239, "name" =>  "Sao Tome and Principe"],
            ["sortname"  => "SA",   "phonecode" =>   966, "name" =>  "Saudi Arabia"],
            ["sortname"  => "SN",   "phonecode" =>   221, "name" =>  "Senegal"],
            ["sortname"  => "RS",   "phonecode" =>   381, "name" =>  "Serbia"],
            ["sortname"  => "SC",   "phonecode" =>   248, "name" =>  "Seychelles"],
            ["sortname"  => "SL",   "phonecode" =>   232, "name" =>  "Sierra Leone"],
            ["sortname"  => "SG",   "phonecode" =>    65, "name" =>  "Singapore"],
            ["sortname"  => "SK",   "phonecode" =>   421, "name" =>  "Slovakia"],
            ["sortname"  => "SI",   "phonecode" =>   386, "name" =>  "Slovenia"],
            ["sortname"  => "XG",   "phonecode" =>    44, "name" =>  "Smaller Territories of the UK"],
            ["sortname"  => "SB",   "phonecode" =>   677, "name" =>  "Solomon Islands"],
            ["sortname"  => "SO",   "phonecode" =>   252, "name" =>  "Somalia"],
            ["sortname"  => "ZA",   "phonecode" =>    27, "name" =>  "South Africa"],
            ["sortname"  => "GS",   "phonecode" =>     0, "name" =>  "South Georgia"],
            ["sortname"  => "SS",   "phonecode" =>   211, "name" =>  "South Sudan"],
            ["sortname"  => "ES",   "phonecode" =>    34, "name" =>  "Spain"],
            ["sortname"  => "LK",   "phonecode" =>    94, "name" =>  "Sri Lanka"],
            ["sortname"  => "SD",   "phonecode" =>   249, "name" =>  "Sudan"],
            ["sortname"  => "SR",   "phonecode" =>   597, "name" =>  "Suriname"],
            ["sortname"  => "SJ",   "phonecode" =>    47, "name" =>  "Svalbard And Jan Mayen Islands"],
            ["sortname"  => "SZ",   "phonecode" =>   268, "name" =>  "Swaziland"],
            ["sortname"  => "SE",   "phonecode" =>    46, "name" =>  "Sweden"],
            ["sortname"  => "CH",   "phonecode" =>    41, "name" =>  "Switzerland"],
            ["sortname"  => "SY",   "phonecode" =>   963, "name" =>  "Syria"],
            ["sortname"  => "TW",   "phonecode" =>   886, "name" =>  "Taiwan"],
            ["sortname"  => "TJ",   "phonecode" =>   992, "name" =>  "Tajikistan"],
            ["sortname"  => "TZ",   "phonecode" =>   255, "name" =>  "Tanzania"],
            ["sortname"  => "TH",   "phonecode" =>    66, "name" =>  "Thailand"],
            ["sortname"  => "TG",   "phonecode" =>   228, "name" =>  "Togo"],
            ["sortname"  => "TK",   "phonecode" =>   690, "name" =>  "Tokelau"],
            ["sortname"  => "TO",   "phonecode" =>   676, "name" =>  "Tonga"],
            ["sortname"  => "TT",   "phonecode" =>  1868, "name" =>  "Trinidad And Tobago"],
            ["sortname"  => "TN",   "phonecode" =>   216, "name" =>  "Tunisia"],
            ["sortname"  => "TR",   "phonecode" =>    90, "name" =>  "Turkey"],
            ["sortname"  => "TM",   "phonecode" =>  7370, "name" =>  "Turkmenistan"],
            ["sortname"  => "TC",   "phonecode" =>  1649, "name" =>  "Turks And Caicos Islands"],
            ["sortname"  => "TV",   "phonecode" =>   688, "name" =>  "Tuvalu"],
            ["sortname"  => "UG",   "phonecode" =>   256, "name" =>  "Uganda"],
            ["sortname"  => "UA",   "phonecode" =>   380, "name" =>  "Ukraine"],
            ["sortname"  => "AE",   "phonecode" =>   971, "name" =>  "United Arab Emirates"],
            ["sortname"  => "GB",   "phonecode" =>    44, "name" =>  "United Kingdom"],
            ["sortname"  => "US",   "phonecode" =>     1, "name" =>  "United States"],
            ["sortname"  => "UM",   "phonecode" =>     1, "name" =>  "United States Minor Outlying Islands"],
            ["sortname"  => "UY",   "phonecode" =>   598, "name" =>  "Uruguay"],
            ["sortname"  => "UZ",   "phonecode" =>   998, "name" =>  "Uzbekistan"],
            ["sortname"  => "VU",   "phonecode" =>   678, "name" =>  "Vanuatu"],
            ["sortname"  => "VA",   "phonecode" =>    39, "name" =>  "Vatican City State (Holy See)"],
            ["sortname"  => "VE",   "phonecode" =>    58, "name" =>  "Venezuela"],
            ["sortname"  => "VN",   "phonecode" =>    84, "name" =>  "Vietnam"],
            ["sortname"  => "VG",   "phonecode" =>  1284, "name" =>  "Virgin Islands (British)"],
            ["sortname"  => "VI",   "phonecode" =>  1340, "name" =>  "Virgin Islands (US)"],
            ["sortname"  => "WF",   "phonecode" =>   681, "name" =>  "Wallis And Futuna Islands"],
            ["sortname"  => "EH",   "phonecode" =>   212, "name" =>  "Western Sahara"],
            ["sortname"  => "YE",   "phonecode" =>   967, "name" =>  "Yemen"],
            ["sortname"  => "YU",   "phonecode" =>    38, "name" =>  "Yugoslavia"],
            ["sortname"  => "ZM",   "phonecode" =>   260, "name" =>  "Zambia"],
            ["sortname"  => "ZW",   "phonecode" =>   263, "name" =>  "Zimbabwe"]        
        ];
        foreach($countries as $country)
        {
            Country::create(array(
                'sortname' => $country['sortname'],
                'phonecode' => $country['phonecode'],
                'name' => $country['name']
            ));
        }
    }
}
